%% Defines surface
%Surface from Cazals article
U = [0 0 0 0 0 1 1 1 1 1];
V = [0 0 0 0 0 1 1 1 1 1];
k = 4;
l = 4;
P        = [0 1/4 2/4 3/4 1;   0  1/4 2/4 3/4 4/4;   0  1/4 2/4 3/4 4/4;   0  1/4 2/4 3/4 4/4;  0 1/4 2/4 3/4 1];
P(:,:,2) = [0  0   0   0  0;  1/4 1/4 1/4 1/4 1/4;  2/4 2/4 2/4 2/4 2/4;  3/4 3/4 3/4 3/4 3/4;  1  1   1   1  1];
P(:,:,3) = [0  0   0   0  0;   0   1  -1  -1   0 ;   0  -1   1   1   0 ;   0   1  -1   1   0 ;  0  0   0   0  0];
P(:,:,4) = [1  1   1   1  1;   1   1   1   1   1 ;   1   1   1   1   1 ;   1   1   1   1   1 ;  1  1   1   1  1];
%corrects parameters
P(:,:,1) = transpose(P(:,:,1));
P(:,:,2) = transpose(P(:,:,2));
P(:,:,3) = transpose(P(:,:,3));
P(:,:,4) = transpose(P(:,:,4));
%Puts everything on homogenous coordinates
PW(:,:,1)   = P(:,:,4).*P(:,:,1);
PW(:,:,2)   = P(:,:,4).*P(:,:,2);
PW(:,:,3)   = P(:,:,4).*P(:,:,3);
PW(:,:,4)   = P(:,:,4);
    
u=0.1
v=0.2

%% Surface operations
%- partial derivatives of the surface (order 1 to 4)
%- Use squeeze(DS(c,d,:))' to get vector of partial derivative values
DS = derivative_order_cd_NURBS_surface_test(u,v,U,V,PW,k+1,l+1,5,5);
    
%% First fundamental form and its partial derivatives
[E,Eu,Ev,Euu,Euv,Evv,...
 F,Fu,Fv,Fuu,Fuv,Fvv,...
 G,Gu,Gv,Guu,Guv,Gvv] = first_fundamental_form(squeeze(DS(2,1,:))',squeeze(DS(1,2,:))',...
                                               squeeze(DS(3,1,:))',squeeze(DS(2,2,:))',squeeze(DS(1,2,:))',...
                                               squeeze(DS(4,1,:))',squeeze(DS(3,2,:))',squeeze(DS(2,3,:))',squeeze(DS(1,4,:))');

%% Surface normal, Rational Surface Normal (bar) and its partial derivatives
[N,barN,...
 barNu,barNv,...
 barNuu,barNuv,barNvv] = surface_normal(squeeze(DS(2,1,:))',squeeze(DS(1,2,:))',...
                                        squeeze(DS(3,1,:))',squeeze(DS(2,2,:))',squeeze(DS(1,2,:))',...
                                        squeeze(DS(4,1,:))',squeeze(DS(3,2,:))',squeeze(DS(2,3,:))',squeeze(DS(1,4,:))');
                                    
%% Second fundamental form, rational Second fundamental form (bar) and its partial derivatives
[e,bare,...
 bareu,barev,bareuu,bareuv,barevv,...
 f,barf,...
 barfu,barfv,barfuu,barfuv,barfvv,...
 g,barg,...
 bargu,bargv,barguu,barguv,bargvv] = second_fundamental_form(squeeze(DS(3,1,:))',squeeze(DS(2,2,:))',squeeze(DS(1,2,:))',...
                                                             squeeze(DS(4,1,:))',squeeze(DS(3,2,:))',squeeze(DS(2,3,:))',squeeze(DS(1,4,:))',...
                                                             squeeze(DS(5,1,:))',squeeze(DS(4,2,:))',squeeze(DS(3,3,:))',squeeze(DS(2,4,:))',squeeze(DS(1,5,:))',...
                                                             N,barN,barNu,barNv,barNuu,barNuv,barNvv);
   
%% Principal curvatures coefficients and its partial derivatives
[A,Au,Av,Auu,Auv,Avv,...
 B,barB,barBu,barBv,barBuu,barBuv,barBvv,...
 C,barC,barCu,barCv,barCuu,barCuv,barCvv] = auxiliary_ABC(E,Eu,Ev,Euu,Euv,Evv,...
                                                          F,Fu,Fv,Fuu,Fuv,Fvv,...
                                                          G,Gu,Gv,Guu,Guv,Gvv,...
                                                          e,bare,bareu,barev,bareuu,bareuv,barevv,...
                                                          f,barf,barfu,barfv,barfuu,barfuv,barfvv,...
                                                          g,barg,bargu,bargv,barguu,barguv,bargvv);

%% Rational coefficients for ridges and umbilics
[Pu,Puu,Puv,Pv,Pvu,Pvv,...
 Ru,Ruu,Ruv,Rv,Rvu,Rvv,...
 Q,Qu,Qv] = auxiliary_PRQ(A,Au,Av,Auu,Auv,Avv,...
                          barB,barBu,barBv,barBuu,barBuv,barBvv,...
                          barC,barCu,barCv,barCuu,barCuv,barCvv);
    