function [surfacePoint] = the_coeficients_of_a_point_on_surface(x)
    u = x(1);
    v = x(2);

    %% Defines surface
    %Surface from Cazals article
    U = [0 0 0 0 0 1 1 1 1 1];
    V = [0 0 0 0 0 1 1 1 1 1];
    k = 4;
    l = 4;
    P        = [0 1/4 2/4 3/4 1;   0  1/4 2/4 3/4 4/4;   0  1/4 2/4 3/4 4/4;   0  1/4 2/4 3/4 4/4;  0 1/4 2/4 3/4 1];
    P(:,:,2) = [0  0   0   0  0;  1/4 1/4 1/4 1/4 1/4;  2/4 2/4 2/4 2/4 2/4;  3/4 3/4 3/4 3/4 3/4;  1  1   1   1  1];
    P(:,:,3) = [0  0   0   0  0;   0   1  -1  -1   0 ;   0  -1   1   1   0 ;   0   1  -1   1   0 ;  0  0   0   0  0];
    P(:,:,4) = [1  1   1   1  1;   1   1   1   1   1 ;   1   1   1   1   1 ;   1   1   1   1   1 ;  1  1   1   1  1];
    %corrects parameters
    P(:,:,1) = transpose(P(:,:,1));
    P(:,:,2) = transpose(P(:,:,2));
    P(:,:,3) = transpose(P(:,:,3));
    P(:,:,4) = transpose(P(:,:,4));
    %Puts everything on homogenous coordinates
    PW(:,:,1)   = P(:,:,4).*P(:,:,1);
    PW(:,:,2)   = P(:,:,4).*P(:,:,2);
    PW(:,:,3)   = P(:,:,4).*P(:,:,3);
    PW(:,:,4)   = P(:,:,4);

    %% All the coefficients associated to the point (u,v) will be a field in this struct
    surfacePoint = struct;
    
    %% Surface operations
    %- partial derivatives of the surface (order 1 to 4)
    %- Use squeeze(surfpoint.DS(c,d,:))' to get vector of partial derivative values
    surfacePoint.DS = derivative_order_cd_NURBS_surface(u,v,U,V,PW,k+1,l+1,5,5);

    %% First fundamental form and its partial derivatives
    [surfacePoint.E,surfacePoint.Eu,surfacePoint.Ev,surfacePoint.Euu,surfacePoint.Euv,surfacePoint.Evv,...
     surfacePoint.F,surfacePoint.Fu,surfacePoint.Fv,surfacePoint.Fuu,surfacePoint.Fuv,surfacePoint.Fvv,...
     surfacePoint.G,surfacePoint.Gu,surfacePoint.Gv,surfacePoint.Guu,surfacePoint.Guv,surfacePoint.Gvv] = first_fundamental_form(squeeze(surfacePoint.DS(2,1,:))',squeeze(surfacePoint.DS(1,2,:))',...
                                                                                                                                 squeeze(surfacePoint.DS(3,1,:))',squeeze(surfacePoint.DS(2,2,:))',squeeze(surfacePoint.DS(1,3,:))',...
                                                                                                                                 squeeze(surfacePoint.DS(4,1,:))',squeeze(surfacePoint.DS(3,2,:))',squeeze(surfacePoint.DS(2,3,:))',squeeze(surfacePoint.DS(1,4,:))');

    %% Surface normal, Rational Surface Normal (bar) and its partial derivatives
    [surfacePoint.N,surfacePoint.barN,...
     surfacePoint.barNu,surfacePoint.barNv,...
     surfacePoint.barNuu,surfacePoint.barNuv,surfacePoint.barNvv] = surface_normal(squeeze(surfacePoint.DS(2,1,:))',squeeze(surfacePoint.DS(1,2,:))',...
                                                                                   squeeze(surfacePoint.DS(3,1,:))',squeeze(surfacePoint.DS(2,2,:))',squeeze(surfacePoint.DS(1,3,:))',...
                                                                                   squeeze(surfacePoint.DS(4,1,:))',squeeze(surfacePoint.DS(3,2,:))',squeeze(surfacePoint.DS(2,3,:))',squeeze(surfacePoint.DS(1,4,:))');

    %% Second fundamental form, rational Second fundamental form (bar) and its partial derivatives
    [surfacePoint.e,surfacePoint.bare,...
     surfacePoint.bareu,surfacePoint.barev,surfacePoint.bareuu,surfacePoint.bareuv,surfacePoint.barevv,...
     surfacePoint.f,surfacePoint.barf,...
     surfacePoint.barfu,surfacePoint.barfv,surfacePoint.barfuu,surfacePoint.barfuv,surfacePoint.barfvv,...
     surfacePoint.g,surfacePoint.barg,...
     surfacePoint.bargu,surfacePoint.bargv,surfacePoint.barguu,surfacePoint.barguv,surfacePoint.bargvv] = second_fundamental_form(squeeze(surfacePoint.DS(3,1,:))',squeeze(surfacePoint.DS(2,2,:))',squeeze(surfacePoint.DS(1,3,:))',...
                                                                                                                                  squeeze(surfacePoint.DS(4,1,:))',squeeze(surfacePoint.DS(3,2,:))',squeeze(surfacePoint.DS(2,3,:))',squeeze(surfacePoint.DS(1,4,:))',...
                                                                                                                                  squeeze(surfacePoint.DS(5,1,:))',squeeze(surfacePoint.DS(4,2,:))',squeeze(surfacePoint.DS(3,3,:))',squeeze(surfacePoint.DS(2,4,:))',squeeze(surfacePoint.DS(1,5,:))',...
                                                                                                                                  surfacePoint.N,surfacePoint.barN,surfacePoint.barNu,surfacePoint.barNv,surfacePoint.barNuu,surfacePoint.barNuv,surfacePoint.barNvv);

    %% Principal curvatures coefficients and its partial derivatives
    [surfacePoint.A,surfacePoint.Au,surfacePoint.Av,surfacePoint.Auu,surfacePoint.Auv,surfacePoint.Avv,...
     surfacePoint.B,surfacePoint.barB,surfacePoint.barBu,surfacePoint.barBv,surfacePoint.barBuu,surfacePoint.barBuv,surfacePoint.barBvv,...
     surfacePoint.C,surfacePoint.barC,surfacePoint.barCu,surfacePoint.barCv,surfacePoint.barCuu,surfacePoint.barCuv,surfacePoint.barCvv] = auxiliary_ABC(surfacePoint.E,surfacePoint.Eu,surfacePoint.Ev,surfacePoint.Euu,surfacePoint.Euv,surfacePoint.Evv,...
                                                                                                                                                         surfacePoint.F,surfacePoint.Fu,surfacePoint.Fv,surfacePoint.Fuu,surfacePoint.Fuv,surfacePoint.Fvv,...
                                                                                                                                                         surfacePoint.G,surfacePoint.Gu,surfacePoint.Gv,surfacePoint.Guu,surfacePoint.Guv,surfacePoint.Gvv,...
                                                                                                                                                         surfacePoint.e,surfacePoint.bare,surfacePoint.bareu,surfacePoint.barev,surfacePoint.bareuu,surfacePoint.bareuv,surfacePoint.barevv,...
                                                                                                                                                         surfacePoint.f,surfacePoint.barf,surfacePoint.barfu,surfacePoint.barfv,surfacePoint.barfuu,surfacePoint.barfuv,surfacePoint.barfvv,...
                                                                                                                                                         surfacePoint.g,surfacePoint.barg,surfacePoint.bargu,surfacePoint.bargv,surfacePoint.barguu,surfacePoint.barguv,surfacePoint.bargvv);

    %% Rational coefficients for ridges and umbilics
    [surfacePoint.Pu,surfacePoint.Puu,surfacePoint.Puv,surfacePoint.Pv,surfacePoint.Pvu,surfacePoint.Pvv,...
     surfacePoint.Ru,surfacePoint.Ruu,surfacePoint.Ruv,surfacePoint.Rv,surfacePoint.Rvu,surfacePoint.Rvv,...
     surfacePoint.Q,surfacePoint.Qu,surfacePoint.Qv] = auxiliary_PRQ(surfacePoint.A,surfacePoint.Au,surfacePoint.Av,surfacePoint.Auu,surfacePoint.Auv,surfacePoint.Avv,...
                                                                     surfacePoint.barB,surfacePoint.barBu,surfacePoint.barBv,surfacePoint.barBuu,surfacePoint.barBuv,surfacePoint.barBvv,...
                                                                     surfacePoint.barC,surfacePoint.barCu,surfacePoint.barCv,surfacePoint.barCuu,surfacePoint.barCuv,surfacePoint.barCvv);
end